---
title: "HW03 - Daniel Krochmal"
author: "Daniel Krochmal"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load libraries}
library("ggplot2")
library("magrittr")
```

## My plot

```{r load dataset}
yiip.df <- (
  read.csv("yiip_size-exclusion.csv", header = TRUE, sep = ",") %>%
    subset(vol > 8 & vol < 25)
)

```

```{r}
ggplot(data = yiip.df, aes(fill = complex, color = complex)) +
  
  geom_ribbon(aes(x = vol, ymin = 0, ymax = a280), alpha = 0.3) +
  
  theme_classic() +
  
    labs(
      title = "Purification of YiiP-antibody complex by size exclusion chromatography",
      subtitle = "Column: Superose 6 10/300 GL",
      x = "Elution volume (ml)",
      y = "A280 (mAu)"
    ) +

  scale_x_continuous(breaks = seq(0, 25, by = 5)) +
  
  theme(
    legend.position = c(0.2, 0.8),
    legend.title = element_blank(),
    legend.text = element_text(size = 8),
    #legend.background = element_rect(color = "black", size = 0.2),
    axis.text.x = element_text(size = 10),
    axis.text.y = element_text(size = 10),
    
    panel.border = element_rect(color = "black", size = 1, fill = NA)
    ) +
  
  annotate(geom = "text",
           x = 12.5,
           y = 19,
           label = "Fab complexes \nwith YiiP target present") +
  
  annotate(geom = "text",
           x = 21,
           y = 40,
           label = "Fab complexes \nwith YiiP target missing", face = "bold") +

  annotate(geom = "curve",
    x = 12.5,
    y = 15,
    xend = 13,
    yend = 5,
    curvature = -0.2,
    size = 0.6,
    arrow = arrow(length = unit(0.2, "cm"), type = "closed")) +
  
  annotate(geom = "curve",
    x = 21,
    y = 35,
    xend = 19,
    yend = 25,
    curvature = -0.4,
    size = 0.6,
    arrow = arrow(length = unit(0.2, "cm"), type = "closed"))

```
